import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';import {handleYouTube} from './youtube-relay.js';
function setup(){const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./youtube-schema.sql',import.meta.url),'utf8'));return {db,env:{DB:{prepare(sql){return {bind(...values){return {async first(){return db.prepare(sql).get(...values) || null;},async run(){return {meta:{changes:Number(db.prepare(sql).run(...values).changes)}};}};}};}}}};}
const SITE='https://yesslashno.github.io',sample={videoId:'dQw4w9WgXcQ',title:'A test song',channel:'Test artist',position:12,duration:120,paused:false,ad:false};
const request=(path,method='GET',token,body,origin=SITE)=>new Request('https://relay.test'+path,{method,headers:{Origin:origin,...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1'},...(body!==undefined?{body:JSON.stringify(body)}:{})});
test('cloud pairs separate read/write keys and save only the latest authorized frame',async()=>{const {db,env}=setup();try{const create=await handleYouTube(request('/api/session','POST'),env,1000);assert.equal(create.status,201);const pair=await create.json();assert.match(pair.readToken,/^[a-f0-9]{48}$/);assert.notEqual(pair.readToken,pair.writeToken);const stored=db.prepare('SELECT * FROM youtube_sessions').get();assert.notEqual(stored.read_hash,pair.readToken);assert.notEqual(stored.write_hash,pair.writeToken);assert.equal((await handleYouTube(request('/api/playback','GET',pair.writeToken),env,2000)).status,401);assert.equal((await handleYouTube(request('/api/playback','POST',pair.readToken,sample),env,2000)).status,401);assert.equal((await handleYouTube(request('/api/playback','POST',pair.writeToken,{...sample,unwanted:'not stored'}),env,2000)).status,200);assert.deepEqual(await (await handleYouTube(request('/api/playback','GET',pair.readToken),env,3500)).json(),{playback:sample,ageMs:1500});await handleYouTube(request('/api/playback','POST',pair.writeToken,null),env,4000);assert.equal((await (await handleYouTube(request('/api/playback','GET',pair.readToken),env,4500)).json()).playback,null);assert.equal((await handleYouTube(request('/api/playback','DELETE',pair.readToken),env,5000)).status,200);assert.equal((await handleYouTube(request('/api/playback','POST',pair.writeToken,sample),env,5001)).status,401);}finally{db.close();}});
test('expiry, bad origins, oversized updates and malformed clocks are rejected',async()=>{const {db,env}=setup();try{assert.equal((await handleYouTube(request('/api/session','POST',null,null,'https://example.com'),env)).status,403);assert.equal((await handleYouTube(request('/api/session','POST',null,null,''),env)).status,403);const pair=await (await handleYouTube(request('/api/session','POST'),env,1000)).json();assert.equal((await handleYouTube(request('/api/playback','GET',pair.readToken),env,pair.expiresAt)).status,401);assert.equal((await handleYouTube(request('/api/playback','POST',pair.writeToken,{...sample,position:-1}),env,2000)).status,400);assert.equal((await handleYouTube(request('/api/playback','POST',pair.writeToken,'x'.repeat(5000)),env,2000)).status,413);assert.equal((await handleYouTube(request('/api/playback','GET','spotify-token'),env)).status,401);}finally{db.close();}});
test('creation rate limits, CORS and configuration failures are handled',async()=>{const {db,env}=setup();try{for(let i=0;i<10;i++)assert.equal((await handleYouTube(request('/api/session','POST'),env,1000)).status,201);assert.equal((await handleYouTube(request('/api/session','POST'),env,1000)).status,429);const preflight=await handleYouTube(request('/api/playback','OPTIONS'),env);assert.equal(preflight.status,204);assert.equal(preflight.headers.get('access-control-allow-origin'),SITE);assert.equal(preflight.headers.get('cache-control'),'no-store');assert.equal((await handleYouTube(request('/api/playback'),{})).status,503);}finally{db.close();}});

test('six-digit pairing gives only the waiting iPad a viewer key and keeps the laptop pairing',async()=>{
 const {db,env}=setup();try{
 const {handleDevice}=await import('./youtube-relay.js');const pair=await (await handleYouTube(request('/api/session','POST'),env,1000)).json();
 const started=await handleDevice(request('/api/device/start','POST'),env,2000);assert.equal(started.status,201);const device=await started.json();assert.match(device.code,/^\d{6}$/);assert.match(device.pollToken,/^[a-f0-9]{48}$/);
 assert.deepEqual(await (await handleDevice(request('/api/device/status','GET',device.pollToken),env,2100)).json(),{pending:true});
 assert.equal((await handleDevice(request('/api/device/approve','POST',pair.writeToken,{code:device.code}),env,2200)).status,401);
 assert.equal((await handleDevice(request('/api/device/approve','POST',pair.readToken,{code:device.code}),env,2300)).status,200);
 const result=await (await handleDevice(request('/api/device/status','GET',device.pollToken),env,2400)).json();assert.equal(result.readToken,pair.readToken);assert.equal(result.writeToken,undefined);assert.equal(result.expiresAt,pair.expiresAt);
 // A delivery retry succeeds; the six-digit code cannot be used to overwrite the linked screen.
 assert.equal((await handleDevice(request('/api/device/status','GET',device.pollToken),env,2500)).status,200);assert.equal((await handleDevice(request('/api/device/approve','POST',pair.readToken,{code:device.code}),env,2600)).status,404);
 assert.equal((await handleYouTube(request('/api/playback','GET',device.pollToken),env,2700)).status,401);
 await handleDevice(request('/api/device/status','DELETE',device.pollToken),env,2800);assert.equal((await handleDevice(request('/api/device/status','GET',device.pollToken),env,2900)).status,410);
 assert.equal(db.prepare('SELECT read_token FROM youtube_devices').get().read_token,null);assert.equal((await handleYouTube(request('/api/playback','GET',pair.readToken),env,3000)).status,200);
 }finally{db.close();}
});
test('short-code expiry, cancellation, guessing limits and untrusted origins are rejected',async()=>{
 const {db,env}=setup();try{const {handleDevice}=await import('./youtube-relay.js');const pair=await (await handleYouTube(request('/api/session','POST'),env,1000)).json();
 assert.equal((await handleDevice(request('/api/device/start','POST',null,null,'https://example.com'),env,2000)).status,403);
 const device=await (await handleDevice(request('/api/device/start','POST'),env,2000)).json();assert.equal((await handleDevice(request('/api/device/status','GET',device.pollToken),env,device.expiresAt)).status,410);assert.equal((await handleDevice(request('/api/device/approve','POST',pair.readToken,{code:device.code}),env,device.expiresAt)).status,404);
 for(let i=0;i<9;i++)assert.equal((await handleDevice(request('/api/device/approve','POST',pair.readToken,{code:'000000'}),env,device.expiresAt+1)).status,404);
 assert.equal((await handleDevice(request('/api/device/approve','POST',pair.readToken,{code:'000000'}),env,device.expiresAt+2)).status,429);
 }finally{db.close();}
});
test('cancelling codes does not bypass creation limits; invalid bodies and revoked pairings fail',async()=>{
 const {db,env}=setup();try{const {handleDevice}=await import('./youtube-relay.js');const pair=await (await handleYouTube(request('/api/session','POST'),env,1000)).json();
 const first=await (await handleDevice(request('/api/device/start','POST'),env,2000)).json();assert.equal((await handleDevice(request('/api/device/approve','POST',pair.readToken,{code:'123 456'}),env,2100)).status,400);
 await handleDevice(request('/api/device/approve','POST',pair.readToken,{code:first.code}),env,2200);await handleYouTube(request('/api/playback','DELETE',pair.readToken),env,2300);assert.equal((await handleDevice(request('/api/device/status','GET',first.pollToken),env,2400)).status,410);
 for(let i=0;i<9;i++){const r=await handleDevice(request('/api/device/start','POST'),env,3000);assert.equal(r.status,201);const d=await r.json();await handleDevice(request('/api/device/status','DELETE',d.pollToken),env,3001);}
 assert.equal((await handleDevice(request('/api/device/start','POST'),env,3002)).status,429);
 }finally{db.close();}
});
